# Autogenerated. Do not modify.
#
# Profile: 21.212.0
# Main-field components only (subfield-gated components omitted — see Stage 2 D).
"""Profile component registry for decode-time expansion.

Generated from the bundled Garmin Profile spreadsheet by ``gen-profile``.
Key: ``(global_message_number, source_field_id)`` → component tuple (LSB first).
"""

from __future__ import annotations

from fit_tool.field_component import FieldComponent

# Coverage: every main-field component source in Profile Messages sheet.
PROFILE_COMPONENT_SOURCE_COUNT = 37

PROFILE_COMPONENTS: dict[tuple[int, int], tuple[FieldComponent, ...]] = {
    # session.avg_speed (field 14) → enhanced_avg_speed
    (18, 14): (
        FieldComponent(field_id=124, accumulate=False, bits=16, scale=1000.0, offset=0.0),
    ),
    # session.max_speed (field 15) → enhanced_max_speed
    (18, 15): (
        FieldComponent(field_id=125, accumulate=False, bits=16, scale=1000.0, offset=0.0),
    ),
    # session.avg_altitude (field 49) → enhanced_avg_altitude
    (18, 49): (
        FieldComponent(field_id=126, accumulate=False, bits=16, scale=5.0, offset=500.0),
    ),
    # session.max_altitude (field 50) → enhanced_max_altitude
    (18, 50): (
        FieldComponent(field_id=128, accumulate=False, bits=16, scale=5.0, offset=500.0),
    ),
    # session.min_altitude (field 71) → enhanced_min_altitude
    (18, 71): (
        FieldComponent(field_id=127, accumulate=False, bits=16, scale=5.0, offset=500.0),
    ),
    # session.avg_respiration_rate (field 147) → enhanced_avg_respiration_rate
    (18, 147): (
        FieldComponent(field_id=169, accumulate=False, bits=8, scale=1.0, offset=0.0),
    ),
    # session.max_respiration_rate (field 148) → enhanced_max_respiration_rate
    (18, 148): (
        FieldComponent(field_id=170, accumulate=False, bits=8, scale=1.0, offset=0.0),
    ),
    # session.min_respiration_rate (field 149) → enhanced_min_respiration_rate
    (18, 149): (
        FieldComponent(field_id=180, accumulate=False, bits=8, scale=1.0, offset=0.0),
    ),
    # lap.avg_speed (field 13) → enhanced_avg_speed
    (19, 13): (
        FieldComponent(field_id=110, accumulate=False, bits=16, scale=1000.0, offset=0.0),
    ),
    # lap.max_speed (field 14) → enhanced_max_speed
    (19, 14): (
        FieldComponent(field_id=111, accumulate=False, bits=16, scale=1000.0, offset=0.0),
    ),
    # lap.avg_altitude (field 42) → enhanced_avg_altitude
    (19, 42): (
        FieldComponent(field_id=112, accumulate=False, bits=16, scale=5.0, offset=500.0),
    ),
    # lap.max_altitude (field 43) → enhanced_max_altitude
    (19, 43): (
        FieldComponent(field_id=114, accumulate=False, bits=16, scale=5.0, offset=500.0),
    ),
    # lap.min_altitude (field 62) → enhanced_min_altitude
    (19, 62): (
        FieldComponent(field_id=113, accumulate=False, bits=16, scale=5.0, offset=500.0),
    ),
    # lap.avg_respiration_rate (field 147) → enhanced_avg_respiration_rate
    (19, 147): (
        FieldComponent(field_id=136, accumulate=False, bits=8, scale=1.0, offset=0.0),
    ),
    # lap.max_respiration_rate (field 148) → enhanced_max_respiration_rate
    (19, 148): (
        FieldComponent(field_id=137, accumulate=False, bits=8, scale=1.0, offset=0.0),
    ),
    # record.altitude (field 2) → enhanced_altitude
    (20, 2): (
        FieldComponent(field_id=78, accumulate=False, bits=16, scale=5.0, offset=500.0),
    ),
    # record.speed (field 6) → enhanced_speed
    (20, 6): (
        FieldComponent(field_id=73, accumulate=False, bits=16, scale=1000.0, offset=0.0),
    ),
    # record.compressed_speed_distance (field 8) → speed, distance
    (20, 8): (
        FieldComponent(field_id=6, accumulate=False, bits=12, scale=100.0, offset=0.0),
        FieldComponent(field_id=5, accumulate=True, bits=12, scale=16.0, offset=0.0),
    ),
    # record.cycles (field 18) → total_cycles
    (20, 18): (
        FieldComponent(field_id=19, accumulate=True, bits=8, scale=1.0, offset=0.0),
    ),
    # record.compressed_accumulated_power (field 28) → accumulated_power
    (20, 28): (
        FieldComponent(field_id=29, accumulate=True, bits=16, scale=1.0, offset=0.0),
    ),
    # record.respiration_rate (field 99) → enhanced_respiration_rate
    (20, 99): (
        FieldComponent(field_id=108, accumulate=False, bits=8, scale=1.0, offset=0.0),
    ),
    # event.data16 (field 2) → data
    (21, 2): (
        FieldComponent(field_id=3, accumulate=False, bits=16, scale=1.0, offset=0.0),
    ),
    # monitoring.current_activity_type_intensity (field 24) → activity_type, intensity
    (55, 24): (
        FieldComponent(field_id=5, accumulate=False, bits=5, scale=1.0, offset=0.0),
        FieldComponent(field_id=28, accumulate=False, bits=3, scale=1.0, offset=0.0),
    ),
    # ant_rx.mesg_data (field 2) → channel_number, data, data, data, data, data, data, data, data
    (80, 2): (
        FieldComponent(field_id=3, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
    ),
    # ant_tx.mesg_data (field 2) → channel_number, data, data, data, data, data, data, data, data
    (81, 2): (
        FieldComponent(field_id=3, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=8, scale=1.0, offset=0.0),
    ),
    # length.avg_respiration_rate (field 24) → enhanced_avg_respiration_rate
    (101, 24): (
        FieldComponent(field_id=22, accumulate=False, bits=8, scale=1.0, offset=0.0),
    ),
    # length.max_respiration_rate (field 25) → enhanced_max_respiration_rate
    (101, 25): (
        FieldComponent(field_id=23, accumulate=False, bits=8, scale=1.0, offset=0.0),
    ),
    # hr.time256 (field 1) → fractional_timestamp
    (132, 1): (
        FieldComponent(field_id=0, accumulate=False, bits=8, scale=256.0, offset=0.0),
    ),
    # hr.event_timestamp_12 (field 10) → event_timestamp, event_timestamp, event_timestamp, event_timestamp, event_timestamp, event_timestamp, event_timestamp, event_timestamp, event_timestamp, event_timestamp
    (132, 10): (
        FieldComponent(field_id=9, accumulate=True, bits=12, scale=1024.0, offset=0.0),
        FieldComponent(field_id=9, accumulate=True, bits=12, scale=1024.0, offset=0.0),
        FieldComponent(field_id=9, accumulate=True, bits=12, scale=1024.0, offset=0.0),
        FieldComponent(field_id=9, accumulate=True, bits=12, scale=1024.0, offset=0.0),
        FieldComponent(field_id=9, accumulate=True, bits=12, scale=1024.0, offset=0.0),
        FieldComponent(field_id=9, accumulate=True, bits=12, scale=1024.0, offset=0.0),
        FieldComponent(field_id=9, accumulate=True, bits=12, scale=1024.0, offset=0.0),
        FieldComponent(field_id=9, accumulate=True, bits=12, scale=1024.0, offset=0.0),
        FieldComponent(field_id=9, accumulate=True, bits=12, scale=1024.0, offset=0.0),
        FieldComponent(field_id=9, accumulate=True, bits=12, scale=1024.0, offset=0.0),
    ),
    # segment_lap.avg_altitude (field 34) → enhanced_avg_altitude
    (142, 34): (
        FieldComponent(field_id=91, accumulate=False, bits=16, scale=5.0, offset=500.0),
    ),
    # segment_lap.max_altitude (field 35) → enhanced_max_altitude
    (142, 35): (
        FieldComponent(field_id=92, accumulate=False, bits=16, scale=5.0, offset=500.0),
    ),
    # segment_lap.min_altitude (field 54) → enhanced_min_altitude
    (142, 54): (
        FieldComponent(field_id=93, accumulate=False, bits=16, scale=5.0, offset=500.0),
    ),
    # segment_point.altitude (field 4) → enhanced_altitude
    (150, 4): (
        FieldComponent(field_id=6, accumulate=False, bits=16, scale=5.0, offset=500.0),
    ),
    # exd_data_field_configuration.concept_field (field 1) → field_id, concept_count
    (201, 1): (
        FieldComponent(field_id=2, accumulate=False, bits=4, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=4, scale=1.0, offset=0.0),
    ),
    # exd_data_concept_configuration.concept_field (field 1) → field_id, concept_index
    (202, 1): (
        FieldComponent(field_id=2, accumulate=False, bits=4, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=4, scale=1.0, offset=0.0),
    ),
    # jump.speed (field 7) → enhanced_speed
    (285, 7): (
        FieldComponent(field_id=8, accumulate=False, bits=16, scale=1000.0, offset=0.0),
    ),
    # raw_bbi.data (field 1) → time, quality, gap, time, quality, gap, time, quality, gap, time, quality, gap, time, quality, gap, time, quality, gap, time, quality, gap, time, quality, gap, time, quality, gap, time, quality, gap, time, quality, gap, time, quality, gap, time, quality, gap, time, quality, gap, time, quality, gap
    (372, 1): (
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=2, accumulate=False, bits=14, scale=1.0, offset=0.0),
        FieldComponent(field_id=3, accumulate=False, bits=1, scale=1.0, offset=0.0),
        FieldComponent(field_id=4, accumulate=False, bits=1, scale=1.0, offset=0.0),
    ),
}

PROFILE_COMPONENT_KEYS: frozenset[tuple[int, int]] = frozenset(PROFILE_COMPONENTS)

