# Autogenerated. Do not modify.
#
# Profile: 21.205.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class BarometerDataMessage(DataMessage):
    """BarometerDataMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``BarometerDataMessage()`` — create path: growable fields, no wire definition.
    * ``BarometerDataMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 209
    NAME = 'barometer_data'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=BarometerDataMessage.NAME,
                         global_id=BarometerDataMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        TimestampField(
            size=0,
            growable=True), 
        BarometerDataTimestampMsField(
            size=0,
            growable=True), 
        BarometerDataSampleTimeOffsetField(
            size=0,
            growable=True), 
        BarometerDataBaroPresField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        TimestampField(
            size=cls._field_size_from_definition(
                definition_message, TimestampField.ID),
            growable=False), 
        BarometerDataTimestampMsField(
            size=cls._field_size_from_definition(
                definition_message, BarometerDataTimestampMsField.ID),
            growable=False), 
        BarometerDataSampleTimeOffsetField(
            size=cls._field_size_from_definition(
                definition_message, BarometerDataSampleTimeOffsetField.ID),
            growable=False), 
        BarometerDataBaroPresField(
            size=cls._field_size_from_definition(
                definition_message, BarometerDataBaroPresField.ID),
            growable=False)
        ])
        message.growable = False
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message



# timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @property
    def timestamp(self) -> Optional[int]:
        field = self.get_field(TimestampField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None


    # timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @timestamp.setter
    def timestamp(self, value: int):
        field = self.get_field(TimestampField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def timestamp_ms(self) -> Optional[int]:
        field = self.get_field(BarometerDataTimestampMsField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @timestamp_ms.setter
    def timestamp_ms(self, value: int):
        field = self.get_field(BarometerDataTimestampMsField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def sample_time_offset(self) -> Optional[list[int]]:
        field = self.get_field(BarometerDataSampleTimeOffsetField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @sample_time_offset.setter
    def sample_time_offset(self, value: list[int]):
        field = self.get_field(BarometerDataSampleTimeOffsetField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def baro_pres(self) -> Optional[list[int]]:
        field = self.get_field(BarometerDataBaroPresField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @baro_pres.setter
    def baro_pres(self, value: list[int]):
        field = self.get_field(BarometerDataBaroPresField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    





class BarometerDataTimestampMsField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='timestamp_ms',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'ms',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class BarometerDataSampleTimeOffsetField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='sample_time_offset',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'ms',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class BarometerDataBaroPresField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='baro_pres',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'Pa',
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )