# Autogenerated. Do not modify.
#
# Profile: 21.212.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class BikeProfileMessage(DataMessage):
    """BikeProfileMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``BikeProfileMessage()`` — create path: growable fields, no wire definition.
    * ``BikeProfileMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 6
    NAME = 'bike_profile'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=BikeProfileMessage.NAME,
                         global_id=BikeProfileMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        MessageIndexField(
            size=0,
            growable=True), 
        BikeProfileNameField(
            size=0,
            growable=True), 
        BikeProfileSportField(
            size=0,
            growable=True), 
        BikeProfileSubSportField(
            size=0,
            growable=True), 
        BikeProfileOdometerField(
            size=0,
            growable=True), 
        BikeProfileBikeSpdAntIdField(
            size=0,
            growable=True), 
        BikeProfileBikeCadAntIdField(
            size=0,
            growable=True), 
        BikeProfileBikeSpdcadAntIdField(
            size=0,
            growable=True), 
        BikeProfileBikePowerAntIdField(
            size=0,
            growable=True), 
        BikeProfileCustomWheelsizeField(
            size=0,
            growable=True), 
        BikeProfileAutoWheelsizeField(
            size=0,
            growable=True), 
        BikeProfileBikeWeightField(
            size=0,
            growable=True), 
        BikeProfilePowerCalFactorField(
            size=0,
            growable=True), 
        BikeProfileAutoWheelCalField(
            size=0,
            growable=True), 
        BikeProfileAutoPowerZeroField(
            size=0,
            growable=True), 
        BikeProfileIdField(
            size=0,
            growable=True), 
        BikeProfileSpdEnabledField(
            size=0,
            growable=True), 
        BikeProfileCadEnabledField(
            size=0,
            growable=True), 
        BikeProfileSpdcadEnabledField(
            size=0,
            growable=True), 
        BikeProfilePowerEnabledField(
            size=0,
            growable=True), 
        BikeProfileCrankLengthField(
            size=0,
            growable=True), 
        BikeProfileEnabledField(
            size=0,
            growable=True), 
        BikeProfileBikeSpdAntIdTransTypeField(
            size=0,
            growable=True), 
        BikeProfileBikeCadAntIdTransTypeField(
            size=0,
            growable=True), 
        BikeProfileBikeSpdcadAntIdTransTypeField(
            size=0,
            growable=True), 
        BikeProfileBikePowerAntIdTransTypeField(
            size=0,
            growable=True), 
        BikeProfileOdometerRolloverField(
            size=0,
            growable=True), 
        BikeProfileFrontGearNumField(
            size=0,
            growable=True), 
        BikeProfileFrontGearField(
            size=0,
            growable=True), 
        BikeProfileRearGearNumField(
            size=0,
            growable=True), 
        BikeProfileRearGearField(
            size=0,
            growable=True), 
        BikeProfileShimanoDi2EnabledField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        MessageIndexField(
            size=cls._field_size_from_definition(
                definition_message, MessageIndexField.ID),
            growable=False), 
        BikeProfileNameField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileNameField.ID),
            growable=False), 
        BikeProfileSportField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileSportField.ID),
            growable=False), 
        BikeProfileSubSportField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileSubSportField.ID),
            growable=False), 
        BikeProfileOdometerField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileOdometerField.ID),
            growable=False), 
        BikeProfileBikeSpdAntIdField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileBikeSpdAntIdField.ID),
            growable=False), 
        BikeProfileBikeCadAntIdField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileBikeCadAntIdField.ID),
            growable=False), 
        BikeProfileBikeSpdcadAntIdField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileBikeSpdcadAntIdField.ID),
            growable=False), 
        BikeProfileBikePowerAntIdField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileBikePowerAntIdField.ID),
            growable=False), 
        BikeProfileCustomWheelsizeField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileCustomWheelsizeField.ID),
            growable=False), 
        BikeProfileAutoWheelsizeField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileAutoWheelsizeField.ID),
            growable=False), 
        BikeProfileBikeWeightField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileBikeWeightField.ID),
            growable=False), 
        BikeProfilePowerCalFactorField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfilePowerCalFactorField.ID),
            growable=False), 
        BikeProfileAutoWheelCalField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileAutoWheelCalField.ID),
            growable=False), 
        BikeProfileAutoPowerZeroField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileAutoPowerZeroField.ID),
            growable=False), 
        BikeProfileIdField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileIdField.ID),
            growable=False), 
        BikeProfileSpdEnabledField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileSpdEnabledField.ID),
            growable=False), 
        BikeProfileCadEnabledField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileCadEnabledField.ID),
            growable=False), 
        BikeProfileSpdcadEnabledField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileSpdcadEnabledField.ID),
            growable=False), 
        BikeProfilePowerEnabledField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfilePowerEnabledField.ID),
            growable=False), 
        BikeProfileCrankLengthField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileCrankLengthField.ID),
            growable=False), 
        BikeProfileEnabledField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileEnabledField.ID),
            growable=False), 
        BikeProfileBikeSpdAntIdTransTypeField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileBikeSpdAntIdTransTypeField.ID),
            growable=False), 
        BikeProfileBikeCadAntIdTransTypeField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileBikeCadAntIdTransTypeField.ID),
            growable=False), 
        BikeProfileBikeSpdcadAntIdTransTypeField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileBikeSpdcadAntIdTransTypeField.ID),
            growable=False), 
        BikeProfileBikePowerAntIdTransTypeField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileBikePowerAntIdTransTypeField.ID),
            growable=False), 
        BikeProfileOdometerRolloverField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileOdometerRolloverField.ID),
            growable=False), 
        BikeProfileFrontGearNumField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileFrontGearNumField.ID),
            growable=False), 
        BikeProfileFrontGearField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileFrontGearField.ID),
            growable=False), 
        BikeProfileRearGearNumField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileRearGearNumField.ID),
            growable=False), 
        BikeProfileRearGearField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileRearGearField.ID),
            growable=False), 
        BikeProfileShimanoDi2EnabledField(
            size=cls._field_size_from_definition(
                definition_message, BikeProfileShimanoDi2EnabledField.ID),
            growable=False)
        ])
        message.growable = False
        # Keep definition field ids not present in the Profile schema (Stage 2 E).
        message.retain_unknown_fields()
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message




    @property
    def message_index(self) -> Optional[int]:
        field = self.get_field(MessageIndexField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @message_index.setter
    def message_index(self, value: int):
        field = self.get_field(MessageIndexField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def bike_profile_name(self) -> Optional[str]:
        field = self.get_field(BikeProfileNameField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @bike_profile_name.setter
    def bike_profile_name(self, value: str):
        field = self.get_field(BikeProfileNameField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def sport(self) -> Optional[Sport]:
        field = self.get_field(BikeProfileSportField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @sport.setter
    def sport(self, value: Sport):
        field = self.get_field(BikeProfileSportField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def sub_sport(self) -> Optional[SubSport]:
        field = self.get_field(BikeProfileSubSportField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @sub_sport.setter
    def sub_sport(self, value: SubSport):
        field = self.get_field(BikeProfileSubSportField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def odometer(self) -> Optional[float]:
        field = self.get_field(BikeProfileOdometerField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @odometer.setter
    def odometer(self, value: float):
        field = self.get_field(BikeProfileOdometerField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def bike_spd_ant_id(self) -> Optional[int]:
        field = self.get_field(BikeProfileBikeSpdAntIdField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @bike_spd_ant_id.setter
    def bike_spd_ant_id(self, value: int):
        field = self.get_field(BikeProfileBikeSpdAntIdField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def bike_cad_ant_id(self) -> Optional[int]:
        field = self.get_field(BikeProfileBikeCadAntIdField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @bike_cad_ant_id.setter
    def bike_cad_ant_id(self, value: int):
        field = self.get_field(BikeProfileBikeCadAntIdField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def bike_spdcad_ant_id(self) -> Optional[int]:
        field = self.get_field(BikeProfileBikeSpdcadAntIdField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @bike_spdcad_ant_id.setter
    def bike_spdcad_ant_id(self, value: int):
        field = self.get_field(BikeProfileBikeSpdcadAntIdField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def bike_power_ant_id(self) -> Optional[int]:
        field = self.get_field(BikeProfileBikePowerAntIdField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @bike_power_ant_id.setter
    def bike_power_ant_id(self, value: int):
        field = self.get_field(BikeProfileBikePowerAntIdField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def custom_wheelsize(self) -> Optional[float]:
        field = self.get_field(BikeProfileCustomWheelsizeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @custom_wheelsize.setter
    def custom_wheelsize(self, value: float):
        field = self.get_field(BikeProfileCustomWheelsizeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def auto_wheelsize(self) -> Optional[float]:
        field = self.get_field(BikeProfileAutoWheelsizeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @auto_wheelsize.setter
    def auto_wheelsize(self, value: float):
        field = self.get_field(BikeProfileAutoWheelsizeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def bike_weight(self) -> Optional[float]:
        field = self.get_field(BikeProfileBikeWeightField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @bike_weight.setter
    def bike_weight(self, value: float):
        field = self.get_field(BikeProfileBikeWeightField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def power_cal_factor(self) -> Optional[float]:
        field = self.get_field(BikeProfilePowerCalFactorField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @power_cal_factor.setter
    def power_cal_factor(self, value: float):
        field = self.get_field(BikeProfilePowerCalFactorField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def auto_wheel_cal(self) -> Optional[bool]:
        field = self.get_field(BikeProfileAutoWheelCalField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @auto_wheel_cal.setter
    def auto_wheel_cal(self, value: bool):
        field = self.get_field(BikeProfileAutoWheelCalField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def auto_power_zero(self) -> Optional[bool]:
        field = self.get_field(BikeProfileAutoPowerZeroField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @auto_power_zero.setter
    def auto_power_zero(self, value: bool):
        field = self.get_field(BikeProfileAutoPowerZeroField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def id(self) -> Optional[int]:
        field = self.get_field(BikeProfileIdField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @id.setter
    def id(self, value: int):
        field = self.get_field(BikeProfileIdField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def spd_enabled(self) -> Optional[bool]:
        field = self.get_field(BikeProfileSpdEnabledField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @spd_enabled.setter
    def spd_enabled(self, value: bool):
        field = self.get_field(BikeProfileSpdEnabledField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def cad_enabled(self) -> Optional[bool]:
        field = self.get_field(BikeProfileCadEnabledField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @cad_enabled.setter
    def cad_enabled(self, value: bool):
        field = self.get_field(BikeProfileCadEnabledField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def spdcad_enabled(self) -> Optional[bool]:
        field = self.get_field(BikeProfileSpdcadEnabledField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @spdcad_enabled.setter
    def spdcad_enabled(self, value: bool):
        field = self.get_field(BikeProfileSpdcadEnabledField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def power_enabled(self) -> Optional[bool]:
        field = self.get_field(BikeProfilePowerEnabledField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @power_enabled.setter
    def power_enabled(self, value: bool):
        field = self.get_field(BikeProfilePowerEnabledField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def crank_length(self) -> Optional[float]:
        field = self.get_field(BikeProfileCrankLengthField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @crank_length.setter
    def crank_length(self, value: float):
        field = self.get_field(BikeProfileCrankLengthField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def enabled(self) -> Optional[bool]:
        field = self.get_field(BikeProfileEnabledField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @enabled.setter
    def enabled(self, value: bool):
        field = self.get_field(BikeProfileEnabledField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def bike_spd_ant_id_trans_type(self) -> Optional[int]:
        field = self.get_field(BikeProfileBikeSpdAntIdTransTypeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @bike_spd_ant_id_trans_type.setter
    def bike_spd_ant_id_trans_type(self, value: int):
        field = self.get_field(BikeProfileBikeSpdAntIdTransTypeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def bike_cad_ant_id_trans_type(self) -> Optional[int]:
        field = self.get_field(BikeProfileBikeCadAntIdTransTypeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @bike_cad_ant_id_trans_type.setter
    def bike_cad_ant_id_trans_type(self, value: int):
        field = self.get_field(BikeProfileBikeCadAntIdTransTypeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def bike_spdcad_ant_id_trans_type(self) -> Optional[int]:
        field = self.get_field(BikeProfileBikeSpdcadAntIdTransTypeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @bike_spdcad_ant_id_trans_type.setter
    def bike_spdcad_ant_id_trans_type(self, value: int):
        field = self.get_field(BikeProfileBikeSpdcadAntIdTransTypeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def bike_power_ant_id_trans_type(self) -> Optional[int]:
        field = self.get_field(BikeProfileBikePowerAntIdTransTypeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @bike_power_ant_id_trans_type.setter
    def bike_power_ant_id_trans_type(self, value: int):
        field = self.get_field(BikeProfileBikePowerAntIdTransTypeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def odometer_rollover(self) -> Optional[int]:
        field = self.get_field(BikeProfileOdometerRolloverField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @odometer_rollover.setter
    def odometer_rollover(self, value: int):
        field = self.get_field(BikeProfileOdometerRolloverField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def front_gear_num(self) -> Optional[int]:
        field = self.get_field(BikeProfileFrontGearNumField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @front_gear_num.setter
    def front_gear_num(self, value: int):
        field = self.get_field(BikeProfileFrontGearNumField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def front_gear(self) -> Optional[list[int]]:
        field = self.get_field(BikeProfileFrontGearField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @front_gear.setter
    def front_gear(self, value: list[int]):
        field = self.get_field(BikeProfileFrontGearField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def rear_gear_num(self) -> Optional[int]:
        field = self.get_field(BikeProfileRearGearNumField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @rear_gear_num.setter
    def rear_gear_num(self, value: int):
        field = self.get_field(BikeProfileRearGearNumField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def rear_gear(self) -> Optional[list[int]]:
        field = self.get_field(BikeProfileRearGearField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @rear_gear.setter
    def rear_gear(self, value: list[int]):
        field = self.get_field(BikeProfileRearGearField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def shimano_di2_enabled(self) -> Optional[bool]:
        field = self.get_field(BikeProfileShimanoDi2EnabledField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @shimano_di2_enabled.setter
    def shimano_di2_enabled(self, value: bool):
        field = self.get_field(BikeProfileShimanoDi2EnabledField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    





class BikeProfileNameField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='name',
            field_id=self.ID,
            base_type=BaseType.STRING,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'string',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileSportField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='sport',
            field_id=self.ID,
            base_type=BaseType.ENUM,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'sport',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileSubSportField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='sub_sport',
            field_id=self.ID,
            base_type=BaseType.ENUM,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'sub_sport',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileOdometerField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='odometer',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 100,
                         size = size,
        units = 'm',
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileBikeSpdAntIdField(Field):
    ID = 4

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='bike_spd_ant_id',
            field_id=self.ID,
            base_type=BaseType.UINT16Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint16z',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileBikeCadAntIdField(Field):
    ID = 5

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='bike_cad_ant_id',
            field_id=self.ID,
            base_type=BaseType.UINT16Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint16z',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileBikeSpdcadAntIdField(Field):
    ID = 6

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='bike_spdcad_ant_id',
            field_id=self.ID,
            base_type=BaseType.UINT16Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint16z',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileBikePowerAntIdField(Field):
    ID = 7

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='bike_power_ant_id',
            field_id=self.ID,
            base_type=BaseType.UINT16Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint16z',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileCustomWheelsizeField(Field):
    ID = 8

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='custom_wheelsize',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1000,
                         size = size,
        units = 'm',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileAutoWheelsizeField(Field):
    ID = 9

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='auto_wheelsize',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1000,
                         size = size,
        units = 'm',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileBikeWeightField(Field):
    ID = 10

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='bike_weight',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 10,
                         size = size,
        units = 'kg',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfilePowerCalFactorField(Field):
    ID = 11

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='power_cal_factor',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 10,
                         size = size,
        units = '%',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileAutoWheelCalField(Field):
    ID = 12

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='auto_wheel_cal',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'bool',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileAutoPowerZeroField(Field):
    ID = 13

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='auto_power_zero',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'bool',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileIdField(Field):
    ID = 14

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='id',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileSpdEnabledField(Field):
    ID = 15

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='spd_enabled',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'bool',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileCadEnabledField(Field):
    ID = 16

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='cad_enabled',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'bool',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileSpdcadEnabledField(Field):
    ID = 17

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='spdcad_enabled',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'bool',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfilePowerEnabledField(Field):
    ID = 18

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='power_enabled',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'bool',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileCrankLengthField(Field):
    ID = 19

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='crank_length',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = -110,
                 scale = 2,
                         size = size,
        units = 'mm',
        type_name = 'uint8',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileEnabledField(Field):
    ID = 20

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='enabled',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'bool',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileBikeSpdAntIdTransTypeField(Field):
    ID = 21

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='bike_spd_ant_id_trans_type',
            field_id=self.ID,
            base_type=BaseType.UINT8Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8z',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileBikeCadAntIdTransTypeField(Field):
    ID = 22

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='bike_cad_ant_id_trans_type',
            field_id=self.ID,
            base_type=BaseType.UINT8Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8z',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileBikeSpdcadAntIdTransTypeField(Field):
    ID = 23

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='bike_spdcad_ant_id_trans_type',
            field_id=self.ID,
            base_type=BaseType.UINT8Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8z',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileBikePowerAntIdTransTypeField(Field):
    ID = 24

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='bike_power_ant_id_trans_type',
            field_id=self.ID,
            base_type=BaseType.UINT8Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8z',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileOdometerRolloverField(Field):
    ID = 37

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='odometer_rollover',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileFrontGearNumField(Field):
    ID = 38

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='front_gear_num',
            field_id=self.ID,
            base_type=BaseType.UINT8Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8z',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileFrontGearField(Field):
    ID = 39

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='front_gear',
            field_id=self.ID,
            base_type=BaseType.UINT8Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8z',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileRearGearNumField(Field):
    ID = 40

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='rear_gear_num',
            field_id=self.ID,
            base_type=BaseType.UINT8Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8z',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileRearGearField(Field):
    ID = 41

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='rear_gear',
            field_id=self.ID,
            base_type=BaseType.UINT8Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8z',
        growable = growable,
                   sub_fields = [
        ]
        )


class BikeProfileShimanoDi2EnabledField(Field):
    ID = 44

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='shimano_di2_enabled',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'bool',
        growable = growable,
                   sub_fields = [
        ]
        )