# Autogenerated. Do not modify.
#
# Profile: 21.205.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class DeveloperDataIdMessage(DataMessage):
    """DeveloperDataIdMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``DeveloperDataIdMessage()`` — create path: growable fields, no wire definition.
    * ``DeveloperDataIdMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 207
    NAME = 'developer_data_id'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=DeveloperDataIdMessage.NAME,
                         global_id=DeveloperDataIdMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        DeveloperDataIdDeveloperIdField(
            size=0,
            growable=True), 
        DeveloperDataIdApplicationIdField(
            size=0,
            growable=True), 
        DeveloperDataIdManufacturerIdField(
            size=0,
            growable=True), 
        DeveloperDataIdDeveloperDataIndexField(
            size=0,
            growable=True), 
        DeveloperDataIdApplicationVersionField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        DeveloperDataIdDeveloperIdField(
            size=cls._field_size_from_definition(
                definition_message, DeveloperDataIdDeveloperIdField.ID),
            growable=False), 
        DeveloperDataIdApplicationIdField(
            size=cls._field_size_from_definition(
                definition_message, DeveloperDataIdApplicationIdField.ID),
            growable=False), 
        DeveloperDataIdManufacturerIdField(
            size=cls._field_size_from_definition(
                definition_message, DeveloperDataIdManufacturerIdField.ID),
            growable=False), 
        DeveloperDataIdDeveloperDataIndexField(
            size=cls._field_size_from_definition(
                definition_message, DeveloperDataIdDeveloperDataIndexField.ID),
            growable=False), 
        DeveloperDataIdApplicationVersionField(
            size=cls._field_size_from_definition(
                definition_message, DeveloperDataIdApplicationVersionField.ID),
            growable=False)
        ])
        message.growable = False
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message




    @property
    def developer_id(self) -> Optional[bytes]:
        field = self.get_field(DeveloperDataIdDeveloperIdField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @developer_id.setter
    def developer_id(self, value: bytes):
        field = self.get_field(DeveloperDataIdDeveloperIdField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def application_id(self) -> Optional[bytes]:
        field = self.get_field(DeveloperDataIdApplicationIdField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @application_id.setter
    def application_id(self, value: bytes):
        field = self.get_field(DeveloperDataIdApplicationIdField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def manufacturer_id(self) -> Optional[int]:
        field = self.get_field(DeveloperDataIdManufacturerIdField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @manufacturer_id.setter
    def manufacturer_id(self, value: int):
        field = self.get_field(DeveloperDataIdManufacturerIdField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def developer_data_index(self) -> Optional[int]:
        field = self.get_field(DeveloperDataIdDeveloperDataIndexField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @developer_data_index.setter
    def developer_data_index(self, value: int):
        field = self.get_field(DeveloperDataIdDeveloperDataIndexField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def application_version(self) -> Optional[int]:
        field = self.get_field(DeveloperDataIdApplicationVersionField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @application_version.setter
    def application_version(self, value: int):
        field = self.get_field(DeveloperDataIdApplicationVersionField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    





class DeveloperDataIdDeveloperIdField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='developer_id',
            field_id=self.ID,
            base_type=BaseType.BYTE,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'byte',
        growable = growable,
                   sub_fields = [
        ]
        )


class DeveloperDataIdApplicationIdField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='application_id',
            field_id=self.ID,
            base_type=BaseType.BYTE,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'byte',
        growable = growable,
                   sub_fields = [
        ]
        )


class DeveloperDataIdManufacturerIdField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='manufacturer_id',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'manufacturer',
        growable = growable,
                   sub_fields = [
        ]
        )


class DeveloperDataIdDeveloperDataIndexField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='developer_data_index',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8',
        growable = growable,
                   sub_fields = [
        ]
        )


class DeveloperDataIdApplicationVersionField(Field):
    ID = 4

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='application_version',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )