# Autogenerated. Do not modify.
#
# Profile: 21.212.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class DiveApneaAlarmMessage(DataMessage):
    """DiveApneaAlarmMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``DiveApneaAlarmMessage()`` — create path: growable fields, no wire definition.
    * ``DiveApneaAlarmMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 393
    NAME = 'dive_apnea_alarm'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=DiveApneaAlarmMessage.NAME,
                         global_id=DiveApneaAlarmMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        MessageIndexField(
            size=0,
            growable=True), 
        DiveApneaAlarmDepthField(
            size=0,
            growable=True), 
        DiveApneaAlarmTimeField(
            size=0,
            growable=True), 
        DiveApneaAlarmEnabledField(
            size=0,
            growable=True), 
        DiveApneaAlarmAlarmTypeField(
            size=0,
            growable=True), 
        DiveApneaAlarmSoundField(
            size=0,
            growable=True), 
        DiveApneaAlarmDiveTypesField(
            size=0,
            growable=True), 
        DiveApneaAlarmIdField(
            size=0,
            growable=True), 
        DiveApneaAlarmPopupEnabledField(
            size=0,
            growable=True), 
        DiveApneaAlarmTriggerOnDescentField(
            size=0,
            growable=True), 
        DiveApneaAlarmTriggerOnAscentField(
            size=0,
            growable=True), 
        DiveApneaAlarmRepeatingField(
            size=0,
            growable=True), 
        DiveApneaAlarmSpeedField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        MessageIndexField(
            size=cls._field_size_from_definition(
                definition_message, MessageIndexField.ID),
            growable=False), 
        DiveApneaAlarmDepthField(
            size=cls._field_size_from_definition(
                definition_message, DiveApneaAlarmDepthField.ID),
            growable=False), 
        DiveApneaAlarmTimeField(
            size=cls._field_size_from_definition(
                definition_message, DiveApneaAlarmTimeField.ID),
            growable=False), 
        DiveApneaAlarmEnabledField(
            size=cls._field_size_from_definition(
                definition_message, DiveApneaAlarmEnabledField.ID),
            growable=False), 
        DiveApneaAlarmAlarmTypeField(
            size=cls._field_size_from_definition(
                definition_message, DiveApneaAlarmAlarmTypeField.ID),
            growable=False), 
        DiveApneaAlarmSoundField(
            size=cls._field_size_from_definition(
                definition_message, DiveApneaAlarmSoundField.ID),
            growable=False), 
        DiveApneaAlarmDiveTypesField(
            size=cls._field_size_from_definition(
                definition_message, DiveApneaAlarmDiveTypesField.ID),
            growable=False), 
        DiveApneaAlarmIdField(
            size=cls._field_size_from_definition(
                definition_message, DiveApneaAlarmIdField.ID),
            growable=False), 
        DiveApneaAlarmPopupEnabledField(
            size=cls._field_size_from_definition(
                definition_message, DiveApneaAlarmPopupEnabledField.ID),
            growable=False), 
        DiveApneaAlarmTriggerOnDescentField(
            size=cls._field_size_from_definition(
                definition_message, DiveApneaAlarmTriggerOnDescentField.ID),
            growable=False), 
        DiveApneaAlarmTriggerOnAscentField(
            size=cls._field_size_from_definition(
                definition_message, DiveApneaAlarmTriggerOnAscentField.ID),
            growable=False), 
        DiveApneaAlarmRepeatingField(
            size=cls._field_size_from_definition(
                definition_message, DiveApneaAlarmRepeatingField.ID),
            growable=False), 
        DiveApneaAlarmSpeedField(
            size=cls._field_size_from_definition(
                definition_message, DiveApneaAlarmSpeedField.ID),
            growable=False)
        ])
        message.growable = False
        # Keep definition field ids not present in the Profile schema (Stage 2 E).
        message.retain_unknown_fields()
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message




    @property
    def message_index(self) -> Optional[int]:
        field = self.get_field(MessageIndexField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @message_index.setter
    def message_index(self, value: int):
        field = self.get_field(MessageIndexField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def depth(self) -> Optional[float]:
        field = self.get_field(DiveApneaAlarmDepthField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @depth.setter
    def depth(self, value: float):
        field = self.get_field(DiveApneaAlarmDepthField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def time(self) -> Optional[int]:
        field = self.get_field(DiveApneaAlarmTimeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @time.setter
    def time(self, value: int):
        field = self.get_field(DiveApneaAlarmTimeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def enabled(self) -> Optional[bool]:
        field = self.get_field(DiveApneaAlarmEnabledField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @enabled.setter
    def enabled(self, value: bool):
        field = self.get_field(DiveApneaAlarmEnabledField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def alarm_type(self) -> Optional[DiveAlarmType]:
        field = self.get_field(DiveApneaAlarmAlarmTypeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @alarm_type.setter
    def alarm_type(self, value: DiveAlarmType):
        field = self.get_field(DiveApneaAlarmAlarmTypeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def sound(self) -> Optional[Tone]:
        field = self.get_field(DiveApneaAlarmSoundField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @sound.setter
    def sound(self, value: Tone):
        field = self.get_field(DiveApneaAlarmSoundField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def dive_types(self) -> Optional[list[SubSport]]:
        field = self.get_field(DiveApneaAlarmDiveTypesField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @dive_types.setter
    def dive_types(self, value: list[SubSport]):
        field = self.get_field(DiveApneaAlarmDiveTypesField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def id(self) -> Optional[int]:
        field = self.get_field(DiveApneaAlarmIdField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @id.setter
    def id(self, value: int):
        field = self.get_field(DiveApneaAlarmIdField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def popup_enabled(self) -> Optional[bool]:
        field = self.get_field(DiveApneaAlarmPopupEnabledField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @popup_enabled.setter
    def popup_enabled(self, value: bool):
        field = self.get_field(DiveApneaAlarmPopupEnabledField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def trigger_on_descent(self) -> Optional[bool]:
        field = self.get_field(DiveApneaAlarmTriggerOnDescentField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @trigger_on_descent.setter
    def trigger_on_descent(self, value: bool):
        field = self.get_field(DiveApneaAlarmTriggerOnDescentField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def trigger_on_ascent(self) -> Optional[bool]:
        field = self.get_field(DiveApneaAlarmTriggerOnAscentField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @trigger_on_ascent.setter
    def trigger_on_ascent(self, value: bool):
        field = self.get_field(DiveApneaAlarmTriggerOnAscentField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def repeating(self) -> Optional[bool]:
        field = self.get_field(DiveApneaAlarmRepeatingField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @repeating.setter
    def repeating(self, value: bool):
        field = self.get_field(DiveApneaAlarmRepeatingField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def speed(self) -> Optional[float]:
        field = self.get_field(DiveApneaAlarmSpeedField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @speed.setter
    def speed(self, value: float):
        field = self.get_field(DiveApneaAlarmSpeedField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    





class DiveApneaAlarmDepthField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='depth',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1000,
                         size = size,
        units = 'm',
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class DiveApneaAlarmTimeField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='time',
            field_id=self.ID,
            base_type=BaseType.SINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 's',
        type_name = 'sint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class DiveApneaAlarmEnabledField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='enabled',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'bool',
        growable = growable,
                   sub_fields = [
        ]
        )


class DiveApneaAlarmAlarmTypeField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='alarm_type',
            field_id=self.ID,
            base_type=BaseType.ENUM,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'dive_alarm_type',
        growable = growable,
                   sub_fields = [
        ]
        )


class DiveApneaAlarmSoundField(Field):
    ID = 4

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='sound',
            field_id=self.ID,
            base_type=BaseType.ENUM,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'tone',
        growable = growable,
                   sub_fields = [
        ]
        )


class DiveApneaAlarmDiveTypesField(Field):
    ID = 5

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='dive_types',
            field_id=self.ID,
            base_type=BaseType.ENUM,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'sub_sport',
        growable = growable,
                   sub_fields = [
        ]
        )


class DiveApneaAlarmIdField(Field):
    ID = 6

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='id',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class DiveApneaAlarmPopupEnabledField(Field):
    ID = 7

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='popup_enabled',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'bool',
        growable = growable,
                   sub_fields = [
        ]
        )


class DiveApneaAlarmTriggerOnDescentField(Field):
    ID = 8

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='trigger_on_descent',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'bool',
        growable = growable,
                   sub_fields = [
        ]
        )


class DiveApneaAlarmTriggerOnAscentField(Field):
    ID = 9

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='trigger_on_ascent',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'bool',
        growable = growable,
                   sub_fields = [
        ]
        )


class DiveApneaAlarmRepeatingField(Field):
    ID = 10

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='repeating',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'bool',
        growable = growable,
                   sub_fields = [
        ]
        )


class DiveApneaAlarmSpeedField(Field):
    ID = 11

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='speed',
            field_id=self.ID,
            base_type=BaseType.SINT32,
        offset = 0,
                 scale = 1000,
                         size = size,
        units = 'mps',
        type_name = 'sint32',
        growable = growable,
                   sub_fields = [
        ]
        )