# Autogenerated. Do not modify.
#
# Profile: 21.212.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class ExdScreenConfigurationMessage(DataMessage):
    """ExdScreenConfigurationMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``ExdScreenConfigurationMessage()`` — create path: growable fields, no wire definition.
    * ``ExdScreenConfigurationMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 200
    NAME = 'exd_screen_configuration'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=ExdScreenConfigurationMessage.NAME,
                         global_id=ExdScreenConfigurationMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        ExdScreenConfigurationScreenIndexField(
            size=0,
            growable=True), 
        ExdScreenConfigurationFieldCountField(
            size=0,
            growable=True), 
        ExdScreenConfigurationLayoutField(
            size=0,
            growable=True), 
        ExdScreenConfigurationScreenEnabledField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        ExdScreenConfigurationScreenIndexField(
            size=cls._field_size_from_definition(
                definition_message, ExdScreenConfigurationScreenIndexField.ID),
            growable=False), 
        ExdScreenConfigurationFieldCountField(
            size=cls._field_size_from_definition(
                definition_message, ExdScreenConfigurationFieldCountField.ID),
            growable=False), 
        ExdScreenConfigurationLayoutField(
            size=cls._field_size_from_definition(
                definition_message, ExdScreenConfigurationLayoutField.ID),
            growable=False), 
        ExdScreenConfigurationScreenEnabledField(
            size=cls._field_size_from_definition(
                definition_message, ExdScreenConfigurationScreenEnabledField.ID),
            growable=False)
        ])
        message.growable = False
        # Keep definition field ids not present in the Profile schema (Stage 2 E).
        message.retain_unknown_fields()
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message




    @property
    def screen_index(self) -> Optional[int]:
        field = self.get_field(ExdScreenConfigurationScreenIndexField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @screen_index.setter
    def screen_index(self, value: int):
        field = self.get_field(ExdScreenConfigurationScreenIndexField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def field_count(self) -> Optional[int]:
        field = self.get_field(ExdScreenConfigurationFieldCountField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @field_count.setter
    def field_count(self, value: int):
        field = self.get_field(ExdScreenConfigurationFieldCountField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def layout(self) -> Optional[ExdLayout]:
        field = self.get_field(ExdScreenConfigurationLayoutField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @layout.setter
    def layout(self, value: ExdLayout):
        field = self.get_field(ExdScreenConfigurationLayoutField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def screen_enabled(self) -> Optional[bool]:
        field = self.get_field(ExdScreenConfigurationScreenEnabledField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @screen_enabled.setter
    def screen_enabled(self, value: bool):
        field = self.get_field(ExdScreenConfigurationScreenEnabledField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    





class ExdScreenConfigurationScreenIndexField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='screen_index',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8',
        growable = growable,
                   sub_fields = [
        ]
        )


class ExdScreenConfigurationFieldCountField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='field_count',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8',
        growable = growable,
                   sub_fields = [
        ]
        )


class ExdScreenConfigurationLayoutField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='layout',
            field_id=self.ID,
            base_type=BaseType.ENUM,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'exd_layout',
        growable = growable,
                   sub_fields = [
        ]
        )


class ExdScreenConfigurationScreenEnabledField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='screen_enabled',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'bool',
        growable = growable,
                   sub_fields = [
        ]
        )