# Autogenerated. Do not modify.
#
# Profile: 21.205.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class FileCapabilitiesMessage(DataMessage):
    """FileCapabilitiesMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``FileCapabilitiesMessage()`` — create path: growable fields, no wire definition.
    * ``FileCapabilitiesMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 37
    NAME = 'file_capabilities'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=FileCapabilitiesMessage.NAME,
                         global_id=FileCapabilitiesMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        MessageIndexField(
            size=0,
            growable=True), 
        FileCapabilitiesTypeField(
            size=0,
            growable=True), 
        FileCapabilitiesFlagsField(
            size=0,
            growable=True), 
        FileCapabilitiesDirectoryField(
            size=0,
            growable=True), 
        FileCapabilitiesMaxCountField(
            size=0,
            growable=True), 
        FileCapabilitiesMaxSizeField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        MessageIndexField(
            size=cls._field_size_from_definition(
                definition_message, MessageIndexField.ID),
            growable=False), 
        FileCapabilitiesTypeField(
            size=cls._field_size_from_definition(
                definition_message, FileCapabilitiesTypeField.ID),
            growable=False), 
        FileCapabilitiesFlagsField(
            size=cls._field_size_from_definition(
                definition_message, FileCapabilitiesFlagsField.ID),
            growable=False), 
        FileCapabilitiesDirectoryField(
            size=cls._field_size_from_definition(
                definition_message, FileCapabilitiesDirectoryField.ID),
            growable=False), 
        FileCapabilitiesMaxCountField(
            size=cls._field_size_from_definition(
                definition_message, FileCapabilitiesMaxCountField.ID),
            growable=False), 
        FileCapabilitiesMaxSizeField(
            size=cls._field_size_from_definition(
                definition_message, FileCapabilitiesMaxSizeField.ID),
            growable=False)
        ])
        message.growable = False
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message




    @property
    def message_index(self) -> Optional[int]:
        field = self.get_field(MessageIndexField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @message_index.setter
    def message_index(self, value: int):
        field = self.get_field(MessageIndexField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def type(self) -> Optional[FileType]:
        field = self.get_field(FileCapabilitiesTypeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @type.setter
    def type(self, value: FileType):
        field = self.get_field(FileCapabilitiesTypeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def flags(self) -> Optional[int]:
        field = self.get_field(FileCapabilitiesFlagsField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @flags.setter
    def flags(self, value: int):
        field = self.get_field(FileCapabilitiesFlagsField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def directory(self) -> Optional[str]:
        field = self.get_field(FileCapabilitiesDirectoryField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @directory.setter
    def directory(self, value: str):
        field = self.get_field(FileCapabilitiesDirectoryField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def max_count(self) -> Optional[int]:
        field = self.get_field(FileCapabilitiesMaxCountField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @max_count.setter
    def max_count(self, value: int):
        field = self.get_field(FileCapabilitiesMaxCountField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def max_size(self) -> Optional[int]:
        field = self.get_field(FileCapabilitiesMaxSizeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @max_size.setter
    def max_size(self, value: int):
        field = self.get_field(FileCapabilitiesMaxSizeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    





class FileCapabilitiesTypeField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='type',
            field_id=self.ID,
            base_type=BaseType.ENUM,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'file',
        growable = growable,
                   sub_fields = [
        ]
        )


class FileCapabilitiesFlagsField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='flags',
            field_id=self.ID,
            base_type=BaseType.UINT8Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'file_flags',
        growable = growable,
                   sub_fields = [
        ]
        )


class FileCapabilitiesDirectoryField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='directory',
            field_id=self.ID,
            base_type=BaseType.STRING,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'string',
        growable = growable,
                   sub_fields = [
        ]
        )


class FileCapabilitiesMaxCountField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='max_count',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class FileCapabilitiesMaxSizeField(Field):
    ID = 4

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='max_size',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'bytes',
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )