# Autogenerated. Do not modify.
#
# Profile: 21.205.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class HsaAccelerometerDataMessage(DataMessage):
    """HsaAccelerometerDataMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``HsaAccelerometerDataMessage()`` — create path: growable fields, no wire definition.
    * ``HsaAccelerometerDataMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 302
    NAME = 'hsa_accelerometer_data'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=HsaAccelerometerDataMessage.NAME,
                         global_id=HsaAccelerometerDataMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        TimestampField(
            size=0,
            growable=True), 
        HsaAccelerometerDataTimestampMsField(
            size=0,
            growable=True), 
        HsaAccelerometerDataSamplingIntervalField(
            size=0,
            growable=True), 
        HsaAccelerometerDataAccelXField(
            size=0,
            growable=True), 
        HsaAccelerometerDataAccelYField(
            size=0,
            growable=True), 
        HsaAccelerometerDataAccelZField(
            size=0,
            growable=True), 
        HsaAccelerometerDataTimestamp32kField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        TimestampField(
            size=cls._field_size_from_definition(
                definition_message, TimestampField.ID),
            growable=False), 
        HsaAccelerometerDataTimestampMsField(
            size=cls._field_size_from_definition(
                definition_message, HsaAccelerometerDataTimestampMsField.ID),
            growable=False), 
        HsaAccelerometerDataSamplingIntervalField(
            size=cls._field_size_from_definition(
                definition_message, HsaAccelerometerDataSamplingIntervalField.ID),
            growable=False), 
        HsaAccelerometerDataAccelXField(
            size=cls._field_size_from_definition(
                definition_message, HsaAccelerometerDataAccelXField.ID),
            growable=False), 
        HsaAccelerometerDataAccelYField(
            size=cls._field_size_from_definition(
                definition_message, HsaAccelerometerDataAccelYField.ID),
            growable=False), 
        HsaAccelerometerDataAccelZField(
            size=cls._field_size_from_definition(
                definition_message, HsaAccelerometerDataAccelZField.ID),
            growable=False), 
        HsaAccelerometerDataTimestamp32kField(
            size=cls._field_size_from_definition(
                definition_message, HsaAccelerometerDataTimestamp32kField.ID),
            growable=False)
        ])
        message.growable = False
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message



# timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @property
    def timestamp(self) -> Optional[int]:
        field = self.get_field(TimestampField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None


    # timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @timestamp.setter
    def timestamp(self, value: int):
        field = self.get_field(TimestampField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def timestamp_ms(self) -> Optional[int]:
        field = self.get_field(HsaAccelerometerDataTimestampMsField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @timestamp_ms.setter
    def timestamp_ms(self, value: int):
        field = self.get_field(HsaAccelerometerDataTimestampMsField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def sampling_interval(self) -> Optional[int]:
        field = self.get_field(HsaAccelerometerDataSamplingIntervalField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @sampling_interval.setter
    def sampling_interval(self, value: int):
        field = self.get_field(HsaAccelerometerDataSamplingIntervalField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def accel_x(self) -> Optional[list[float]]:
        field = self.get_field(HsaAccelerometerDataAccelXField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @accel_x.setter
    def accel_x(self, value: list[float]):
        field = self.get_field(HsaAccelerometerDataAccelXField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def accel_y(self) -> Optional[list[float]]:
        field = self.get_field(HsaAccelerometerDataAccelYField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @accel_y.setter
    def accel_y(self, value: list[float]):
        field = self.get_field(HsaAccelerometerDataAccelYField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def accel_z(self) -> Optional[list[float]]:
        field = self.get_field(HsaAccelerometerDataAccelZField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @accel_z.setter
    def accel_z(self, value: list[float]):
        field = self.get_field(HsaAccelerometerDataAccelZField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def timestamp_32k(self) -> Optional[int]:
        field = self.get_field(HsaAccelerometerDataTimestamp32kField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @timestamp_32k.setter
    def timestamp_32k(self, value: int):
        field = self.get_field(HsaAccelerometerDataTimestamp32kField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    





class HsaAccelerometerDataTimestampMsField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='timestamp_ms',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'ms',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class HsaAccelerometerDataSamplingIntervalField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='sampling_interval',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'ms',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class HsaAccelerometerDataAccelXField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='accel_x',
            field_id=self.ID,
            base_type=BaseType.SINT16,
        offset = 0,
                 scale = 1.024,
                         size = size,
        units = 'mG',
        type_name = 'sint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class HsaAccelerometerDataAccelYField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='accel_y',
            field_id=self.ID,
            base_type=BaseType.SINT16,
        offset = 0,
                 scale = 1.024,
                         size = size,
        units = 'mG',
        type_name = 'sint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class HsaAccelerometerDataAccelZField(Field):
    ID = 4

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='accel_z',
            field_id=self.ID,
            base_type=BaseType.SINT16,
        offset = 0,
                 scale = 1.024,
                         size = size,
        units = 'mG',
        type_name = 'sint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class HsaAccelerometerDataTimestamp32kField(Field):
    ID = 5

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='timestamp_32k',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )