# Autogenerated. Do not modify.
#
# Profile: 21.212.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class MagnetometerDataMessage(DataMessage):
    """MagnetometerDataMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``MagnetometerDataMessage()`` — create path: growable fields, no wire definition.
    * ``MagnetometerDataMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 208
    NAME = 'magnetometer_data'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=MagnetometerDataMessage.NAME,
                         global_id=MagnetometerDataMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        TimestampField(
            size=0,
            growable=True), 
        MagnetometerDataTimestampMsField(
            size=0,
            growable=True), 
        MagnetometerDataSampleTimeOffsetField(
            size=0,
            growable=True), 
        MagnetometerDataMagXField(
            size=0,
            growable=True), 
        MagnetometerDataMagYField(
            size=0,
            growable=True), 
        MagnetometerDataMagZField(
            size=0,
            growable=True), 
        MagnetometerDataCalibratedMagXField(
            size=0,
            growable=True), 
        MagnetometerDataCalibratedMagYField(
            size=0,
            growable=True), 
        MagnetometerDataCalibratedMagZField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        TimestampField(
            size=cls._field_size_from_definition(
                definition_message, TimestampField.ID),
            growable=False), 
        MagnetometerDataTimestampMsField(
            size=cls._field_size_from_definition(
                definition_message, MagnetometerDataTimestampMsField.ID),
            growable=False), 
        MagnetometerDataSampleTimeOffsetField(
            size=cls._field_size_from_definition(
                definition_message, MagnetometerDataSampleTimeOffsetField.ID),
            growable=False), 
        MagnetometerDataMagXField(
            size=cls._field_size_from_definition(
                definition_message, MagnetometerDataMagXField.ID),
            growable=False), 
        MagnetometerDataMagYField(
            size=cls._field_size_from_definition(
                definition_message, MagnetometerDataMagYField.ID),
            growable=False), 
        MagnetometerDataMagZField(
            size=cls._field_size_from_definition(
                definition_message, MagnetometerDataMagZField.ID),
            growable=False), 
        MagnetometerDataCalibratedMagXField(
            size=cls._field_size_from_definition(
                definition_message, MagnetometerDataCalibratedMagXField.ID),
            growable=False), 
        MagnetometerDataCalibratedMagYField(
            size=cls._field_size_from_definition(
                definition_message, MagnetometerDataCalibratedMagYField.ID),
            growable=False), 
        MagnetometerDataCalibratedMagZField(
            size=cls._field_size_from_definition(
                definition_message, MagnetometerDataCalibratedMagZField.ID),
            growable=False)
        ])
        message.growable = False
        # Keep definition field ids not present in the Profile schema (Stage 2 E).
        message.retain_unknown_fields()
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message



# timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @property
    def timestamp(self) -> Optional[int]:
        field = self.get_field(TimestampField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None


    # timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @timestamp.setter
    def timestamp(self, value: int):
        field = self.get_field(TimestampField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def timestamp_ms(self) -> Optional[int]:
        field = self.get_field(MagnetometerDataTimestampMsField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @timestamp_ms.setter
    def timestamp_ms(self, value: int):
        field = self.get_field(MagnetometerDataTimestampMsField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def sample_time_offset(self) -> Optional[list[int]]:
        field = self.get_field(MagnetometerDataSampleTimeOffsetField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @sample_time_offset.setter
    def sample_time_offset(self, value: list[int]):
        field = self.get_field(MagnetometerDataSampleTimeOffsetField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def mag_x(self) -> Optional[list[int]]:
        field = self.get_field(MagnetometerDataMagXField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @mag_x.setter
    def mag_x(self, value: list[int]):
        field = self.get_field(MagnetometerDataMagXField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def mag_y(self) -> Optional[list[int]]:
        field = self.get_field(MagnetometerDataMagYField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @mag_y.setter
    def mag_y(self, value: list[int]):
        field = self.get_field(MagnetometerDataMagYField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def mag_z(self) -> Optional[list[int]]:
        field = self.get_field(MagnetometerDataMagZField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @mag_z.setter
    def mag_z(self, value: list[int]):
        field = self.get_field(MagnetometerDataMagZField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def calibrated_mag_x(self) -> Optional[list[float]]:
        field = self.get_field(MagnetometerDataCalibratedMagXField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @calibrated_mag_x.setter
    def calibrated_mag_x(self, value: list[float]):
        field = self.get_field(MagnetometerDataCalibratedMagXField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def calibrated_mag_y(self) -> Optional[list[float]]:
        field = self.get_field(MagnetometerDataCalibratedMagYField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @calibrated_mag_y.setter
    def calibrated_mag_y(self, value: list[float]):
        field = self.get_field(MagnetometerDataCalibratedMagYField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def calibrated_mag_z(self) -> Optional[list[float]]:
        field = self.get_field(MagnetometerDataCalibratedMagZField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @calibrated_mag_z.setter
    def calibrated_mag_z(self, value: list[float]):
        field = self.get_field(MagnetometerDataCalibratedMagZField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    





class MagnetometerDataTimestampMsField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='timestamp_ms',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'ms',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class MagnetometerDataSampleTimeOffsetField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='sample_time_offset',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'ms',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class MagnetometerDataMagXField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='mag_x',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'counts',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class MagnetometerDataMagYField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='mag_y',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'counts',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class MagnetometerDataMagZField(Field):
    ID = 4

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='mag_z',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'counts',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class MagnetometerDataCalibratedMagXField(Field):
    ID = 5

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='calibrated_mag_x',
            field_id=self.ID,
            base_type=BaseType.FLOAT32,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'G',
        type_name = 'float32',
        growable = growable,
                   sub_fields = [
        ]
        )


class MagnetometerDataCalibratedMagYField(Field):
    ID = 6

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='calibrated_mag_y',
            field_id=self.ID,
            base_type=BaseType.FLOAT32,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'G',
        type_name = 'float32',
        growable = growable,
                   sub_fields = [
        ]
        )


class MagnetometerDataCalibratedMagZField(Field):
    ID = 7

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='calibrated_mag_z',
            field_id=self.ID,
            base_type=BaseType.FLOAT32,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'G',
        type_name = 'float32',
        growable = growable,
                   sub_fields = [
        ]
        )