# Autogenerated. Do not modify.
#
# Profile: 21.212.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class MemoGlobMessage(DataMessage):
    """MemoGlobMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``MemoGlobMessage()`` — create path: growable fields, no wire definition.
    * ``MemoGlobMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 145
    NAME = 'memo_glob'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=MemoGlobMessage.NAME,
                         global_id=MemoGlobMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        MemoGlobPartIndexField(
            size=0,
            growable=True), 
        MemoGlobMemoField(
            size=0,
            growable=True), 
        MemoGlobMesgNumField(
            size=0,
            growable=True), 
        MemoGlobParentIndexField(
            size=0,
            growable=True), 
        MemoGlobFieldNumField(
            size=0,
            growable=True), 
        MemoGlobDataField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        MemoGlobPartIndexField(
            size=cls._field_size_from_definition(
                definition_message, MemoGlobPartIndexField.ID),
            growable=False), 
        MemoGlobMemoField(
            size=cls._field_size_from_definition(
                definition_message, MemoGlobMemoField.ID),
            growable=False), 
        MemoGlobMesgNumField(
            size=cls._field_size_from_definition(
                definition_message, MemoGlobMesgNumField.ID),
            growable=False), 
        MemoGlobParentIndexField(
            size=cls._field_size_from_definition(
                definition_message, MemoGlobParentIndexField.ID),
            growable=False), 
        MemoGlobFieldNumField(
            size=cls._field_size_from_definition(
                definition_message, MemoGlobFieldNumField.ID),
            growable=False), 
        MemoGlobDataField(
            size=cls._field_size_from_definition(
                definition_message, MemoGlobDataField.ID),
            growable=False)
        ])
        message.growable = False
        # Keep definition field ids not present in the Profile schema (Stage 2 E).
        message.retain_unknown_fields()
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message




    @property
    def part_index(self) -> Optional[int]:
        field = self.get_field(MemoGlobPartIndexField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @part_index.setter
    def part_index(self, value: int):
        field = self.get_field(MemoGlobPartIndexField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def memo(self) -> Optional[bytes]:
        field = self.get_field(MemoGlobMemoField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @memo.setter
    def memo(self, value: bytes):
        field = self.get_field(MemoGlobMemoField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def mesg_num(self) -> Optional[int]:
        field = self.get_field(MemoGlobMesgNumField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @mesg_num.setter
    def mesg_num(self, value: int):
        field = self.get_field(MemoGlobMesgNumField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def parent_index(self) -> Optional[int]:
        field = self.get_field(MemoGlobParentIndexField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @parent_index.setter
    def parent_index(self, value: int):
        field = self.get_field(MemoGlobParentIndexField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def field_num(self) -> Optional[int]:
        field = self.get_field(MemoGlobFieldNumField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @field_num.setter
    def field_num(self, value: int):
        field = self.get_field(MemoGlobFieldNumField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def data(self) -> Optional[list[int]]:
        field = self.get_field(MemoGlobDataField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @data.setter
    def data(self, value: list[int]):
        field = self.get_field(MemoGlobDataField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    





class MemoGlobPartIndexField(Field):
    ID = 250

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='part_index',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class MemoGlobMemoField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='memo',
            field_id=self.ID,
            base_type=BaseType.BYTE,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'byte',
        growable = growable,
                   sub_fields = [
        ]
        )


class MemoGlobMesgNumField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='mesg_num',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'mesg_num',
        growable = growable,
                   sub_fields = [
        ]
        )


class MemoGlobParentIndexField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='parent_index',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'message_index',
        growable = growable,
                   sub_fields = [
        ]
        )


class MemoGlobFieldNumField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='field_num',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8',
        growable = growable,
                   sub_fields = [
        ]
        )


class MemoGlobDataField(Field):
    ID = 4

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='data',
            field_id=self.ID,
            base_type=BaseType.UINT8Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8z',
        growable = growable,
                   sub_fields = [
        ]
        )