# Autogenerated. Do not modify.
#
# Profile: 21.205.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class MesgCapabilitiesMessage(DataMessage):
    """MesgCapabilitiesMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``MesgCapabilitiesMessage()`` — create path: growable fields, no wire definition.
    * ``MesgCapabilitiesMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 38
    NAME = 'mesg_capabilities'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=MesgCapabilitiesMessage.NAME,
                         global_id=MesgCapabilitiesMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        MessageIndexField(
            size=0,
            growable=True), 
        MesgCapabilitiesFileField(
            size=0,
            growable=True), 
        MesgCapabilitiesMesgNumField(
            size=0,
            growable=True), 
        MesgCapabilitiesCountTypeField(
            size=0,
            growable=True), 
        MesgCapabilitiesCountField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        MessageIndexField(
            size=cls._field_size_from_definition(
                definition_message, MessageIndexField.ID),
            growable=False), 
        MesgCapabilitiesFileField(
            size=cls._field_size_from_definition(
                definition_message, MesgCapabilitiesFileField.ID),
            growable=False), 
        MesgCapabilitiesMesgNumField(
            size=cls._field_size_from_definition(
                definition_message, MesgCapabilitiesMesgNumField.ID),
            growable=False), 
        MesgCapabilitiesCountTypeField(
            size=cls._field_size_from_definition(
                definition_message, MesgCapabilitiesCountTypeField.ID),
            growable=False), 
        MesgCapabilitiesCountField(
            size=cls._field_size_from_definition(
                definition_message, MesgCapabilitiesCountField.ID),
            growable=False)
        ])
        message.growable = False
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message




    @property
    def message_index(self) -> Optional[int]:
        field = self.get_field(MessageIndexField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @message_index.setter
    def message_index(self, value: int):
        field = self.get_field(MessageIndexField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def file(self) -> Optional[FileType]:
        field = self.get_field(MesgCapabilitiesFileField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @file.setter
    def file(self, value: FileType):
        field = self.get_field(MesgCapabilitiesFileField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def mesg_num(self) -> Optional[int]:
        field = self.get_field(MesgCapabilitiesMesgNumField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @mesg_num.setter
    def mesg_num(self, value: int):
        field = self.get_field(MesgCapabilitiesMesgNumField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def count_type(self) -> Optional[MesgCount]:
        field = self.get_field(MesgCapabilitiesCountTypeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @count_type.setter
    def count_type(self, value: MesgCount):
        field = self.get_field(MesgCapabilitiesCountTypeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def count(self) -> Optional[int]:
        field = self.get_field(MesgCapabilitiesCountField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @count.setter
    def count(self, value: int):
        field = self.get_field(MesgCapabilitiesCountField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    


    @property
    def num_per_file(self) -> Optional[int]:
        field = self.get_field(MesgCapabilitiesCountField.ID)
        type_field = self.get_field(MesgCapabilitiesCountTypeField.ID)

        is_sub_field_valid = type_field and type_field.get_value() in [0]
        if field and field.is_valid() and is_sub_field_valid:
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None

    @num_per_file.setter
    def num_per_file(self, value: int):
        field = self.get_field(MesgCapabilitiesCountField.ID)
        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)


    @property
    def max_per_file(self) -> Optional[int]:
        field = self.get_field(MesgCapabilitiesCountField.ID)
        type_field = self.get_field(MesgCapabilitiesCountTypeField.ID)

        is_sub_field_valid = type_field and type_field.get_value() in [1]
        if field and field.is_valid() and is_sub_field_valid:
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None

    @max_per_file.setter
    def max_per_file(self, value: int):
        field = self.get_field(MesgCapabilitiesCountField.ID)
        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)


    @property
    def max_per_file_type(self) -> Optional[int]:
        field = self.get_field(MesgCapabilitiesCountField.ID)
        type_field = self.get_field(MesgCapabilitiesCountTypeField.ID)

        is_sub_field_valid = type_field and type_field.get_value() in [2]
        if field and field.is_valid() and is_sub_field_valid:
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None

    @max_per_file_type.setter
    def max_per_file_type(self, value: int):
        field = self.get_field(MesgCapabilitiesCountField.ID)
        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)





class MesgCapabilitiesFileField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='file',
            field_id=self.ID,
            base_type=BaseType.ENUM,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'file',
        growable = growable,
                   sub_fields = [
        ]
        )


class MesgCapabilitiesMesgNumField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='mesg_num',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'mesg_num',
        growable = growable,
                   sub_fields = [
        ]
        )


class MesgCapabilitiesCountTypeField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='count_type',
            field_id=self.ID,
            base_type=BaseType.ENUM,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'mesg_count',
        growable = growable,
                   sub_fields = [
        ]
        )


class MesgCapabilitiesCountField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='count',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        SubField(
            name='num_per_file',
            base_type=BaseType.UINT16,
        scale = 1,
                offset = 0,
        reference_map = {
        MesgCapabilitiesCountTypeField.ID: [0]
        }), 
        SubField(
            name='max_per_file',
            base_type=BaseType.UINT16,
        scale = 1,
                offset = 0,
        reference_map = {
        MesgCapabilitiesCountTypeField.ID: [1]
        }), 
        SubField(
            name='max_per_file_type',
            base_type=BaseType.UINT16,
        scale = 1,
                offset = 0,
        reference_map = {
        MesgCapabilitiesCountTypeField.ID: [2]
        })
        ]
        )