# Autogenerated. Do not modify.
#
# Profile: 21.205.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class ObdiiDataMessage(DataMessage):
    """ObdiiDataMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``ObdiiDataMessage()`` — create path: growable fields, no wire definition.
    * ``ObdiiDataMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 174
    NAME = 'obdii_data'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=ObdiiDataMessage.NAME,
                         global_id=ObdiiDataMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        TimestampField(
            size=0,
            growable=True), 
        ObdiiDataTimestampMsField(
            size=0,
            growable=True), 
        ObdiiDataTimeOffsetField(
            size=0,
            growable=True), 
        ObdiiDataPidField(
            size=0,
            growable=True), 
        ObdiiDataRawDataField(
            size=0,
            growable=True), 
        ObdiiDataPidDataSizeField(
            size=0,
            growable=True), 
        ObdiiDataSystemTimeField(
            size=0,
            growable=True), 
        ObdiiDataStartTimestampField(
            size=0,
            growable=True), 
        ObdiiDataStartTimestampMsField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        TimestampField(
            size=cls._field_size_from_definition(
                definition_message, TimestampField.ID),
            growable=False), 
        ObdiiDataTimestampMsField(
            size=cls._field_size_from_definition(
                definition_message, ObdiiDataTimestampMsField.ID),
            growable=False), 
        ObdiiDataTimeOffsetField(
            size=cls._field_size_from_definition(
                definition_message, ObdiiDataTimeOffsetField.ID),
            growable=False), 
        ObdiiDataPidField(
            size=cls._field_size_from_definition(
                definition_message, ObdiiDataPidField.ID),
            growable=False), 
        ObdiiDataRawDataField(
            size=cls._field_size_from_definition(
                definition_message, ObdiiDataRawDataField.ID),
            growable=False), 
        ObdiiDataPidDataSizeField(
            size=cls._field_size_from_definition(
                definition_message, ObdiiDataPidDataSizeField.ID),
            growable=False), 
        ObdiiDataSystemTimeField(
            size=cls._field_size_from_definition(
                definition_message, ObdiiDataSystemTimeField.ID),
            growable=False), 
        ObdiiDataStartTimestampField(
            size=cls._field_size_from_definition(
                definition_message, ObdiiDataStartTimestampField.ID),
            growable=False), 
        ObdiiDataStartTimestampMsField(
            size=cls._field_size_from_definition(
                definition_message, ObdiiDataStartTimestampMsField.ID),
            growable=False)
        ])
        message.growable = False
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message



# timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @property
    def timestamp(self) -> Optional[int]:
        field = self.get_field(TimestampField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None


    # timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @timestamp.setter
    def timestamp(self, value: int):
        field = self.get_field(TimestampField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def timestamp_ms(self) -> Optional[int]:
        field = self.get_field(ObdiiDataTimestampMsField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @timestamp_ms.setter
    def timestamp_ms(self, value: int):
        field = self.get_field(ObdiiDataTimestampMsField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def time_offset(self) -> Optional[list[int]]:
        field = self.get_field(ObdiiDataTimeOffsetField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @time_offset.setter
    def time_offset(self, value: list[int]):
        field = self.get_field(ObdiiDataTimeOffsetField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def pid(self) -> Optional[int]:
        field = self.get_field(ObdiiDataPidField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @pid.setter
    def pid(self, value: int):
        field = self.get_field(ObdiiDataPidField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def raw_data(self) -> Optional[bytes]:
        field = self.get_field(ObdiiDataRawDataField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @raw_data.setter
    def raw_data(self, value: bytes):
        field = self.get_field(ObdiiDataRawDataField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def pid_data_size(self) -> Optional[list[int]]:
        field = self.get_field(ObdiiDataPidDataSizeField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @pid_data_size.setter
    def pid_data_size(self, value: list[int]):
        field = self.get_field(ObdiiDataPidDataSizeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    

    @property
    def system_time(self) -> Optional[list[int]]:
        field = self.get_field(ObdiiDataSystemTimeField.ID)
        if field and field.is_valid():
            return field.get_values()
        else:
            return None



    @system_time.setter
    def system_time(self, value: list[int]):
        field = self.get_field(ObdiiDataSystemTimeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                field.set_values(value)

    
# timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @property
    def start_timestamp(self) -> Optional[int]:
        field = self.get_field(ObdiiDataStartTimestampField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None


    # timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @start_timestamp.setter
    def start_timestamp(self, value: int):
        field = self.get_field(ObdiiDataStartTimestampField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def start_timestamp_ms(self) -> Optional[int]:
        field = self.get_field(ObdiiDataStartTimestampMsField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @start_timestamp_ms.setter
    def start_timestamp_ms(self, value: int):
        field = self.get_field(ObdiiDataStartTimestampMsField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    





class ObdiiDataTimestampMsField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='timestamp_ms',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'ms',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class ObdiiDataTimeOffsetField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='time_offset',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'ms',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class ObdiiDataPidField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='pid',
            field_id=self.ID,
            base_type=BaseType.BYTE,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'byte',
        growable = growable,
                   sub_fields = [
        ]
        )


class ObdiiDataRawDataField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='raw_data',
            field_id=self.ID,
            base_type=BaseType.BYTE,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'byte',
        growable = growable,
                   sub_fields = [
        ]
        )


class ObdiiDataPidDataSizeField(Field):
    ID = 4

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='pid_data_size',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8',
        growable = growable,
                   sub_fields = [
        ]
        )


class ObdiiDataSystemTimeField(Field):
    ID = 5

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='system_time',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class ObdiiDataStartTimestampField(Field):
    ID = 6

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='start_timestamp',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = -631065600000,
                 scale = 0.001,
                         size = size,
        units = 'ms',
        type_name = 'date_time',
        growable = growable,
                   sub_fields = [
        ]
        )


class ObdiiDataStartTimestampMsField(Field):
    ID = 7

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='start_timestamp_ms',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'ms',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )