# Autogenerated. Do not modify.
#
# Profile: 21.205.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class OneDSensorCalibrationMessage(DataMessage):
    """OneDSensorCalibrationMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``OneDSensorCalibrationMessage()`` — create path: growable fields, no wire definition.
    * ``OneDSensorCalibrationMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 210
    NAME = 'one_d_sensor_calibration'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=OneDSensorCalibrationMessage.NAME,
                         global_id=OneDSensorCalibrationMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        TimestampField(
            size=0,
            growable=True), 
        OneDSensorCalibrationSensorTypeField(
            size=0,
            growable=True), 
        OneDSensorCalibrationCalibrationFactorField(
            size=0,
            growable=True), 
        OneDSensorCalibrationCalibrationDivisorField(
            size=0,
            growable=True), 
        OneDSensorCalibrationLevelShiftField(
            size=0,
            growable=True), 
        OneDSensorCalibrationOffsetCalField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        TimestampField(
            size=cls._field_size_from_definition(
                definition_message, TimestampField.ID),
            growable=False), 
        OneDSensorCalibrationSensorTypeField(
            size=cls._field_size_from_definition(
                definition_message, OneDSensorCalibrationSensorTypeField.ID),
            growable=False), 
        OneDSensorCalibrationCalibrationFactorField(
            size=cls._field_size_from_definition(
                definition_message, OneDSensorCalibrationCalibrationFactorField.ID),
            growable=False), 
        OneDSensorCalibrationCalibrationDivisorField(
            size=cls._field_size_from_definition(
                definition_message, OneDSensorCalibrationCalibrationDivisorField.ID),
            growable=False), 
        OneDSensorCalibrationLevelShiftField(
            size=cls._field_size_from_definition(
                definition_message, OneDSensorCalibrationLevelShiftField.ID),
            growable=False), 
        OneDSensorCalibrationOffsetCalField(
            size=cls._field_size_from_definition(
                definition_message, OneDSensorCalibrationOffsetCalField.ID),
            growable=False)
        ])
        message.growable = False
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message



# timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @property
    def timestamp(self) -> Optional[int]:
        field = self.get_field(TimestampField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None


    # timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @timestamp.setter
    def timestamp(self, value: int):
        field = self.get_field(TimestampField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def sensor_type(self) -> Optional[SensorType]:
        field = self.get_field(OneDSensorCalibrationSensorTypeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @sensor_type.setter
    def sensor_type(self, value: SensorType):
        field = self.get_field(OneDSensorCalibrationSensorTypeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def calibration_factor(self) -> Optional[int]:
        field = self.get_field(OneDSensorCalibrationCalibrationFactorField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @calibration_factor.setter
    def calibration_factor(self, value: int):
        field = self.get_field(OneDSensorCalibrationCalibrationFactorField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    


    @property
    def baro_cal_factor(self) -> Optional[int]:
        field = self.get_field(OneDSensorCalibrationCalibrationFactorField.ID)
        type_field = self.get_field(OneDSensorCalibrationSensorTypeField.ID)

        is_sub_field_valid = type_field and type_field.get_value() in [3]
        if field and field.is_valid() and is_sub_field_valid:
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None

    @baro_cal_factor.setter
    def baro_cal_factor(self, value: int):
        field = self.get_field(OneDSensorCalibrationCalibrationFactorField.ID)
        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    @property
    def calibration_divisor(self) -> Optional[int]:
        field = self.get_field(OneDSensorCalibrationCalibrationDivisorField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @calibration_divisor.setter
    def calibration_divisor(self, value: int):
        field = self.get_field(OneDSensorCalibrationCalibrationDivisorField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def level_shift(self) -> Optional[int]:
        field = self.get_field(OneDSensorCalibrationLevelShiftField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @level_shift.setter
    def level_shift(self, value: int):
        field = self.get_field(OneDSensorCalibrationLevelShiftField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def offset_cal(self) -> Optional[int]:
        field = self.get_field(OneDSensorCalibrationOffsetCalField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @offset_cal.setter
    def offset_cal(self, value: int):
        field = self.get_field(OneDSensorCalibrationOffsetCalField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    





class OneDSensorCalibrationSensorTypeField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='sensor_type',
            field_id=self.ID,
            base_type=BaseType.ENUM,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'sensor_type',
        growable = growable,
                   sub_fields = [
        ]
        )


class OneDSensorCalibrationCalibrationFactorField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='calibration_factor',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        SubField(
            name='baro_cal_factor',
            base_type=BaseType.UINT32,
        scale = 1,
                offset = 0,
        units = 'Pa',
        reference_map = {
        OneDSensorCalibrationSensorTypeField.ID: [3]
        })
        ]
        )


class OneDSensorCalibrationCalibrationDivisorField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='calibration_divisor',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'counts',
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class OneDSensorCalibrationLevelShiftField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='level_shift',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class OneDSensorCalibrationOffsetCalField(Field):
    ID = 4

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='offset_cal',
            field_id=self.ID,
            base_type=BaseType.SINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'sint32',
        growable = growable,
                   sub_fields = [
        ]
        )