# Autogenerated. Do not modify.
#
# Profile: 21.205.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class SegmentLeaderboardEntryMessage(DataMessage):
    """SegmentLeaderboardEntryMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``SegmentLeaderboardEntryMessage()`` — create path: growable fields, no wire definition.
    * ``SegmentLeaderboardEntryMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 149
    NAME = 'segment_leaderboard_entry'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=SegmentLeaderboardEntryMessage.NAME,
                         global_id=SegmentLeaderboardEntryMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        MessageIndexField(
            size=0,
            growable=True), 
        SegmentLeaderboardEntryNameField(
            size=0,
            growable=True), 
        SegmentLeaderboardEntryTypeField(
            size=0,
            growable=True), 
        SegmentLeaderboardEntryGroupPrimaryKeyField(
            size=0,
            growable=True), 
        SegmentLeaderboardEntryActivityIdField(
            size=0,
            growable=True), 
        SegmentLeaderboardEntrySegmentTimeField(
            size=0,
            growable=True), 
        SegmentLeaderboardEntryActivityIdStringField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        MessageIndexField(
            size=cls._field_size_from_definition(
                definition_message, MessageIndexField.ID),
            growable=False), 
        SegmentLeaderboardEntryNameField(
            size=cls._field_size_from_definition(
                definition_message, SegmentLeaderboardEntryNameField.ID),
            growable=False), 
        SegmentLeaderboardEntryTypeField(
            size=cls._field_size_from_definition(
                definition_message, SegmentLeaderboardEntryTypeField.ID),
            growable=False), 
        SegmentLeaderboardEntryGroupPrimaryKeyField(
            size=cls._field_size_from_definition(
                definition_message, SegmentLeaderboardEntryGroupPrimaryKeyField.ID),
            growable=False), 
        SegmentLeaderboardEntryActivityIdField(
            size=cls._field_size_from_definition(
                definition_message, SegmentLeaderboardEntryActivityIdField.ID),
            growable=False), 
        SegmentLeaderboardEntrySegmentTimeField(
            size=cls._field_size_from_definition(
                definition_message, SegmentLeaderboardEntrySegmentTimeField.ID),
            growable=False), 
        SegmentLeaderboardEntryActivityIdStringField(
            size=cls._field_size_from_definition(
                definition_message, SegmentLeaderboardEntryActivityIdStringField.ID),
            growable=False)
        ])
        message.growable = False
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message




    @property
    def message_index(self) -> Optional[int]:
        field = self.get_field(MessageIndexField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @message_index.setter
    def message_index(self, value: int):
        field = self.get_field(MessageIndexField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def segment_leaderboard_entry_name(self) -> Optional[str]:
        field = self.get_field(SegmentLeaderboardEntryNameField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @segment_leaderboard_entry_name.setter
    def segment_leaderboard_entry_name(self, value: str):
        field = self.get_field(SegmentLeaderboardEntryNameField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def type(self) -> Optional[SegmentLeaderboardType]:
        field = self.get_field(SegmentLeaderboardEntryTypeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @type.setter
    def type(self, value: SegmentLeaderboardType):
        field = self.get_field(SegmentLeaderboardEntryTypeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def group_primary_key(self) -> Optional[int]:
        field = self.get_field(SegmentLeaderboardEntryGroupPrimaryKeyField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @group_primary_key.setter
    def group_primary_key(self, value: int):
        field = self.get_field(SegmentLeaderboardEntryGroupPrimaryKeyField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def activity_id(self) -> Optional[int]:
        field = self.get_field(SegmentLeaderboardEntryActivityIdField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @activity_id.setter
    def activity_id(self, value: int):
        field = self.get_field(SegmentLeaderboardEntryActivityIdField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def segment_time(self) -> Optional[float]:
        field = self.get_field(SegmentLeaderboardEntrySegmentTimeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @segment_time.setter
    def segment_time(self, value: float):
        field = self.get_field(SegmentLeaderboardEntrySegmentTimeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def activity_id_string(self) -> Optional[str]:
        field = self.get_field(SegmentLeaderboardEntryActivityIdStringField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @activity_id_string.setter
    def activity_id_string(self, value: str):
        field = self.get_field(SegmentLeaderboardEntryActivityIdStringField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    





class SegmentLeaderboardEntryNameField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='name',
            field_id=self.ID,
            base_type=BaseType.STRING,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'string',
        growable = growable,
                   sub_fields = [
        ]
        )


class SegmentLeaderboardEntryTypeField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='type',
            field_id=self.ID,
            base_type=BaseType.ENUM,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'segment_leaderboard_type',
        growable = growable,
                   sub_fields = [
        ]
        )


class SegmentLeaderboardEntryGroupPrimaryKeyField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='group_primary_key',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class SegmentLeaderboardEntryActivityIdField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='activity_id',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class SegmentLeaderboardEntrySegmentTimeField(Field):
    ID = 4

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='segment_time',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1000,
                         size = size,
        units = 's',
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class SegmentLeaderboardEntryActivityIdStringField(Field):
    ID = 5

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='activity_id_string',
            field_id=self.ID,
            base_type=BaseType.STRING,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'string',
        growable = growable,
                   sub_fields = [
        ]
        )