# Autogenerated. Do not modify.
#
# Profile: 21.205.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class TankSummaryMessage(DataMessage):
    """TankSummaryMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``TankSummaryMessage()`` — create path: growable fields, no wire definition.
    * ``TankSummaryMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 323
    NAME = 'tank_summary'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=TankSummaryMessage.NAME,
                         global_id=TankSummaryMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        TimestampField(
            size=0,
            growable=True), 
        TankSummarySensorField(
            size=0,
            growable=True), 
        TankSummaryStartPressureField(
            size=0,
            growable=True), 
        TankSummaryEndPressureField(
            size=0,
            growable=True), 
        TankSummaryVolumeUsedField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        TimestampField(
            size=cls._field_size_from_definition(
                definition_message, TimestampField.ID),
            growable=False), 
        TankSummarySensorField(
            size=cls._field_size_from_definition(
                definition_message, TankSummarySensorField.ID),
            growable=False), 
        TankSummaryStartPressureField(
            size=cls._field_size_from_definition(
                definition_message, TankSummaryStartPressureField.ID),
            growable=False), 
        TankSummaryEndPressureField(
            size=cls._field_size_from_definition(
                definition_message, TankSummaryEndPressureField.ID),
            growable=False), 
        TankSummaryVolumeUsedField(
            size=cls._field_size_from_definition(
                definition_message, TankSummaryVolumeUsedField.ID),
            growable=False)
        ])
        message.growable = False
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message



# timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @property
    def timestamp(self) -> Optional[int]:
        field = self.get_field(TimestampField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None


    # timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @timestamp.setter
    def timestamp(self, value: int):
        field = self.get_field(TimestampField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def sensor(self) -> Optional[int]:
        field = self.get_field(TankSummarySensorField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @sensor.setter
    def sensor(self, value: int):
        field = self.get_field(TankSummarySensorField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def start_pressure(self) -> Optional[float]:
        field = self.get_field(TankSummaryStartPressureField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @start_pressure.setter
    def start_pressure(self, value: float):
        field = self.get_field(TankSummaryStartPressureField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def end_pressure(self) -> Optional[float]:
        field = self.get_field(TankSummaryEndPressureField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @end_pressure.setter
    def end_pressure(self, value: float):
        field = self.get_field(TankSummaryEndPressureField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def volume_used(self) -> Optional[float]:
        field = self.get_field(TankSummaryVolumeUsedField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @volume_used.setter
    def volume_used(self, value: float):
        field = self.get_field(TankSummaryVolumeUsedField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    





class TankSummarySensorField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='sensor',
            field_id=self.ID,
            base_type=BaseType.UINT32Z,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'ant_channel_id',
        growable = growable,
                   sub_fields = [
        ]
        )


class TankSummaryStartPressureField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='start_pressure',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 100,
                         size = size,
        units = 'bar',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class TankSummaryEndPressureField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='end_pressure',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 100,
                         size = size,
        units = 'bar',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class TankSummaryVolumeUsedField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='volume_used',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 100,
                         size = size,
        units = 'L',
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )