# Autogenerated. Do not modify.
#
# Profile: 21.212.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class TotalsMessage(DataMessage):
    """TotalsMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``TotalsMessage()`` — create path: growable fields, no wire definition.
    * ``TotalsMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 33
    NAME = 'totals'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=TotalsMessage.NAME,
                         global_id=TotalsMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        MessageIndexField(
            size=0,
            growable=True), 
        TimestampField(
            size=0,
            growable=True), 
        TotalsTimerTimeField(
            size=0,
            growable=True), 
        TotalsDistanceField(
            size=0,
            growable=True), 
        TotalsCaloriesField(
            size=0,
            growable=True), 
        TotalsSportField(
            size=0,
            growable=True), 
        TotalsElapsedTimeField(
            size=0,
            growable=True), 
        TotalsSessionsField(
            size=0,
            growable=True), 
        TotalsActiveTimeField(
            size=0,
            growable=True), 
        TotalsSportIndexField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        MessageIndexField(
            size=cls._field_size_from_definition(
                definition_message, MessageIndexField.ID),
            growable=False), 
        TimestampField(
            size=cls._field_size_from_definition(
                definition_message, TimestampField.ID),
            growable=False), 
        TotalsTimerTimeField(
            size=cls._field_size_from_definition(
                definition_message, TotalsTimerTimeField.ID),
            growable=False), 
        TotalsDistanceField(
            size=cls._field_size_from_definition(
                definition_message, TotalsDistanceField.ID),
            growable=False), 
        TotalsCaloriesField(
            size=cls._field_size_from_definition(
                definition_message, TotalsCaloriesField.ID),
            growable=False), 
        TotalsSportField(
            size=cls._field_size_from_definition(
                definition_message, TotalsSportField.ID),
            growable=False), 
        TotalsElapsedTimeField(
            size=cls._field_size_from_definition(
                definition_message, TotalsElapsedTimeField.ID),
            growable=False), 
        TotalsSessionsField(
            size=cls._field_size_from_definition(
                definition_message, TotalsSessionsField.ID),
            growable=False), 
        TotalsActiveTimeField(
            size=cls._field_size_from_definition(
                definition_message, TotalsActiveTimeField.ID),
            growable=False), 
        TotalsSportIndexField(
            size=cls._field_size_from_definition(
                definition_message, TotalsSportIndexField.ID),
            growable=False)
        ])
        message.growable = False
        # Keep definition field ids not present in the Profile schema (Stage 2 E).
        message.retain_unknown_fields()
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message




    @property
    def message_index(self) -> Optional[int]:
        field = self.get_field(MessageIndexField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @message_index.setter
    def message_index(self, value: int):
        field = self.get_field(MessageIndexField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    
# timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @property
    def timestamp(self) -> Optional[int]:
        field = self.get_field(TimestampField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None


    # timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @timestamp.setter
    def timestamp(self, value: int):
        field = self.get_field(TimestampField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def timer_time(self) -> Optional[int]:
        field = self.get_field(TotalsTimerTimeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @timer_time.setter
    def timer_time(self, value: int):
        field = self.get_field(TotalsTimerTimeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def distance(self) -> Optional[int]:
        field = self.get_field(TotalsDistanceField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @distance.setter
    def distance(self, value: int):
        field = self.get_field(TotalsDistanceField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def calories(self) -> Optional[int]:
        field = self.get_field(TotalsCaloriesField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @calories.setter
    def calories(self, value: int):
        field = self.get_field(TotalsCaloriesField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def sport(self) -> Optional[Sport]:
        field = self.get_field(TotalsSportField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @sport.setter
    def sport(self, value: Sport):
        field = self.get_field(TotalsSportField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def elapsed_time(self) -> Optional[int]:
        field = self.get_field(TotalsElapsedTimeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @elapsed_time.setter
    def elapsed_time(self, value: int):
        field = self.get_field(TotalsElapsedTimeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def sessions(self) -> Optional[int]:
        field = self.get_field(TotalsSessionsField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @sessions.setter
    def sessions(self, value: int):
        field = self.get_field(TotalsSessionsField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def active_time(self) -> Optional[int]:
        field = self.get_field(TotalsActiveTimeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @active_time.setter
    def active_time(self, value: int):
        field = self.get_field(TotalsActiveTimeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def sport_index(self) -> Optional[int]:
        field = self.get_field(TotalsSportIndexField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @sport_index.setter
    def sport_index(self, value: int):
        field = self.get_field(TotalsSportIndexField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    





class TotalsTimerTimeField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='timer_time',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 's',
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class TotalsDistanceField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='distance',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'm',
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class TotalsCaloriesField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='calories',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'kcal',
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class TotalsSportField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='sport',
            field_id=self.ID,
            base_type=BaseType.ENUM,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'sport',
        growable = growable,
                   sub_fields = [
        ]
        )


class TotalsElapsedTimeField(Field):
    ID = 4

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='elapsed_time',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 's',
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class TotalsSessionsField(Field):
    ID = 5

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='sessions',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class TotalsActiveTimeField(Field):
    ID = 6

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='active_time',
            field_id=self.ID,
            base_type=BaseType.UINT32,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 's',
        type_name = 'uint32',
        growable = growable,
                   sub_fields = [
        ]
        )


class TotalsSportIndexField(Field):
    ID = 9

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='sport_index',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8',
        growable = growable,
                   sub_fields = [
        ]
        )