name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release-pypi:
    name: Release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: "auto"

      - name: Check prerelease
        id: check_version
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/tags/[0-9.]+$ ]]; then
            echo "PRERELEASE=false" >> $GITHUB_OUTPUT
          else
            echo "PRERELEASE=true" >> $GITHUB_OUTPUT
          fi

      - name: Build package
        run: uv build

      - name: Upload artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: fit-tool-wheel
          path: dist/*.whl
          if-no-files-found: error
          retention-days: 15

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Get Changelog
        id: get-changelog
        run: |
          awk '/## Release/{if (flag==1)exit;else;flag=1;next} flag' CHANGELOG.md > .changelog.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: .changelog.md
          draft: false
          prerelease: ${{ steps.check_version.outputs.PRERELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
