name: Release

on:
  push:
    tags:
      - "*"

defaults:
  run:
    # make sure to work on Windows
    shell: bash

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Check prerelease
        id: check_version
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/tags/[0-9.]+$ ]]; then
            echo "PRERELEASE=false" >> $GITHUB_OUTPUT
          else
            echo "PREREERELEASE=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup uv
        uses: astral-sh/setup-uv@v1
        with:
          uv-version: latest

      - name: Build artifacts
        run: uv build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fit-tool-wheel
          path: dist/*.whl
          if-no-files-found: error
          retention-days: 15

      - name: Test Build
        run: |
          uv pip install "fit-tool @ file://$(ls ${GITHUB_WORKSPACE}/dist/*.whl)"
          fittool --help

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ steps.check_version.outputs.PRERELEASE }}
          generate_release_notes: true
